"""
Fix 40 — Captured Request -> Direct Replay Probe.

This validates the key production transition.

For each symbol:
1. Open authenticated Option Chain page in the existing browser context.
2. Select the symbol using #optSymbol.
3. Capture the actual POST generated by iCharts to
   OptionChainTable_Beta_v19.php.
4. Capture its response.
5. Replay the EXACT captured POST through the authenticated
   BrowserContext.request API, using the same URL/body and relevant headers.
6. Compare the captured and replayed Option Chain payloads.

No guessed parameters. No hard-coded ATM. No client-side strike cap.
No scheduler, no XLSX, no production output.

The browser page is used only to establish the request contract. The replay
tests whether the production collector can subsequently avoid browser-page
collection and use direct authenticated requests.
"""

from __future__ import annotations

import asyncio
import json
import time
from urllib.parse import parse_qs

OPTION_CHAIN = "https://www.icharts.in/opt/OptionChain.php"
TABLE_MARKER = "OptionChainTable_Beta_v19.php"


def _form(body):
    try:
        p = parse_qs(body or "", keep_blank_values=True)
        return {k: (v[0] if v else "") for k, v in p.items()}
    except Exception:
        return {}


def _signature(data):
    if not isinstance(data, dict):
        return None
    rows = data.get("aaData") or []
    return {
        "server_symbol": str(data.get("symbol_1", "")),
        "expiry": str(data.get("optExpDate", "")),
        "atm": str(data.get("strikePriceATM", "")),
        "optStrike": str(data.get("optStrike", "")),
        "rows": len(rows) if isinstance(rows, list) else 0,
        "strikes": [
            str(r[32]) for r in rows
            if isinstance(r, list) and len(r) > 32
        ],
    }


async def _capture(context, symbol, timeout_seconds):
    page = await context.new_page()
    captured = {"request": None}

    def on_request(req):
        if TABLE_MARKER in req.url and req.method.upper() == "POST":
            captured["request"] = req

    page.on("request", on_request)

    try:
        await page.goto(
            OPTION_CHAIN,
            wait_until="domcontentloaded",
            timeout=timeout_seconds * 1000,
        )
        await page.wait_for_timeout(1000)

        options = await page.locator("#optSymbol option").evaluate_all(
            """els => els.map(e => String(e.value || '').toUpperCase())"""
        )
        if symbol.upper() not in options:
            raise RuntimeError(
                "Requested symbol is not present in #optSymbol options."
            )

        await page.select_option("#optSymbol", symbol)

        deadline = time.perf_counter() + timeout_seconds
        while captured["request"] is None and time.perf_counter() < deadline:
            await page.wait_for_timeout(100)

        req = captured["request"]
        if req is None:
            raise RuntimeError(
                "iCharts did not generate OptionChainTable_Beta_v19.php POST."
            )

        response = await req.response()
        if response is None:
            raise RuntimeError("Captured request has no response.")

        body = req.post_data or ""
        response_text = await response.text()

        try:
            response_json = json.loads(response_text)
        except Exception as exc:
            raise RuntimeError(
                f"Captured response is not JSON: {exc}; body={response_text[:300]!r}"
            )

        # Only pass headers that are meaningful/safe for a direct replay.
        # Cookies/session authentication remain owned by the Playwright context.
        headers = {
            k: v
            for k, v in req.headers.items()
            if k.lower() in {
                "content-type", "referer", "origin", "x-requested-with",
                "accept"
            }
        }

        return {
            "page": page,
            "request_url": req.url,
            "request_body": body,
            "request_params": _form(body),
            "request_headers": headers,
            "http": response.status,
            "json": response_json,
            "signature": _signature(response_json),
        }

    except Exception:
        await page.close()
        raise


async def _one(context, symbol, timeout_seconds=30):
    started = time.perf_counter()
    page = None
    try:
        cap = await _capture(context, symbol, timeout_seconds)
        page = cap.pop("page")

        # Replay EXACT body and URL. We intentionally do not reconstruct the
        # parameter set.
        replay_headers = dict(cap["request_headers"])
        replay_headers.pop("content-length", None)

        replay = await context.request.post(
            cap["request_url"],
            data=cap["request_body"],
            headers=replay_headers,
            timeout=timeout_seconds * 1000,
        )
        replay_text = await replay.text()

        try:
            replay_json = json.loads(replay_text)
        except Exception as exc:
            return {
                "symbol": symbol,
                "captured_http": cap["http"],
                "replay_http": replay.status,
                "captured_server_symbol": cap["signature"]["server_symbol"],
                "replay_server_symbol": "",
                "captured_atm": cap["signature"]["atm"],
                "replay_atm": "",
                "captured_rows": cap["signature"]["rows"],
                "replay_rows": 0,
                "payload_match": False,
                "pass": False,
                "elapsed_ms": round((time.perf_counter()-started)*1000, 1),
                "error": f"Replay response is not JSON: {exc}; body={replay_text[:300]!r}",
                "captured_request_body": cap["request_body"],
                "captured_request_params": cap["request_params"],
            }

        replay_sig = _signature(replay_json)
        cap_sig = cap["signature"]

        payload_match = replay_sig == cap_sig

        return {
            "symbol": symbol,
            "captured_http": cap["http"],
            "replay_http": replay.status,
            "captured_server_symbol": cap_sig["server_symbol"],
            "replay_server_symbol": replay_sig["server_symbol"],
            "captured_atm": cap_sig["atm"],
            "replay_atm": replay_sig["atm"],
            "captured_rows": cap_sig["rows"],
            "replay_rows": replay_sig["rows"],
            "payload_match": payload_match,
            "captured_strikes": cap_sig["strikes"],
            "replay_strikes": replay_sig["strikes"],
            "captured_expiry": cap_sig["expiry"],
            "replay_expiry": replay_sig["expiry"],
            "captured_optStrike": cap_sig["optStrike"],
            "replay_optStrike": replay_sig["optStrike"],
            "request_url": cap["request_url"],
            "request_params": cap["request_params"],
            "request_headers": cap["request_headers"],
            "pass": (
                cap["http"] == 200
                and replay.status == 200
                and replay_sig["server_symbol"].upper() == symbol.upper()
                and payload_match
            ),
            "elapsed_ms": round((time.perf_counter()-started)*1000, 1),
            "error": "",
        }

    except Exception as exc:
        return {
            "symbol": symbol,
            "pass": False,
            "elapsed_ms": round((time.perf_counter()-started)*1000, 1),
            "error": str(exc),
        }
    finally:
        if page is not None:
            await page.close()


async def run_optionchain_direct_replay_probe(context, symbols, timeout_seconds=30):
    started = time.perf_counter()

    # Sequential because each capture involves changing browser page state.
    results = []
    for symbol in symbols:
        results.append(await _one(context, symbol, timeout_seconds))

    passed = sum(bool(r.get("pass")) for r in results)

    return {
        "test": "Option Chain Captured Request -> Direct Replay Probe",
        "requested": len(symbols),
        "passed": passed,
        "failed": len(symbols) - passed,
        "elapsed_ms": round((time.perf_counter()-started)*1000, 1),
        "results": results,
    }
