"""
Fix 39 — Option Chain Actual Request Capture Probe.

Purpose:
Do not guess/reconstruct the OptionChainTable POST.

For each symbol:
1. Use the existing authenticated Playwright BrowserContext.
2. Open OptionChain.php in a temporary page.
3. Select the symbol through the page's actual #optSymbol control.
4. Listen for the actual OptionChainTable_Beta_v19.php request generated by
   iCharts JavaScript.
5. Capture the exact POST body and relevant headers.
6. Capture the actual response and parse its JSON.
7. Validate server symbol, returned strikes, response ATM, and whether ATM is
   present in the returned strike rows.

This is a sequential state-validation probe. It creates no XLSX, does not run
the scheduler, and does not replay a manually constructed POST.

Important:
The probe does not assume that the hidden ATM/optStrike fields are correct.
The response generated by iCharts is the authority for this test.
"""

from __future__ import annotations

import asyncio
import json
import time
from urllib.parse import parse_qs

OPTION_CHAIN = "https://www.icharts.in/opt/OptionChain.php"
TABLE_MARKER = "OptionChainTable_Beta_v19.php"


def _extract_form(body: str) -> dict:
    try:
        parsed = parse_qs(body or "", keep_blank_values=True)
        return {k: (v[0] if v else "") for k, v in parsed.items()}
    except Exception:
        return {}


async def _read_page_state(page):
    return await page.evaluate(
        """() => {
            const val = (sel) => {
                const e = document.querySelector(sel);
                return e ? String(e.value ?? '') : '';
            };
            return {
                selected_symbol: val('#optSymbol'),
                optExpDate: val('#optExpDate'),
                strikePriceATM: val('#strikePriceATM'),
                centralStrike: val('#centralStrike'),
                optStrike: val('#optStrike'),
                defaultDate: val('#defaultDate'),
                atmstrikesnumber: val('#atmstrikesnumber'),
                atmstrikesnumberfixed: val('#atmstrikesnumberfixed'),
                buttontype: val('[name="buttontype"]'),
                striketype: val('[name="striketype"]:checked'),
                dType: val('#rdDataType'),
            };
        }"""
    )


async def _one(context, symbol: str, timeout_seconds: int = 30) -> dict:
    started = time.perf_counter()
    page = await context.new_page()

    result = {
        "symbol": symbol,
        "selected_symbol": "",
        "request_url": "",
        "request_http": None,
        "request_method": "",
        "request_post_data": "",
        "request_params": {},
        "request_headers": {},
        "captured_expiry": "",
        "captured_optStrike": "",
        "response_ATM": "",
        "response_optStrike": "",
        "server_symbol": "",
        "response_rows": 0,
        "returned_strikes": [],
        "atm_in_returned_strikes": False,
        "pass": False,
        "elapsed_ms": 0,
        "error": "",
    }

    try:
        await page.goto(
            OPTION_CHAIN,
            wait_until="domcontentloaded",
            timeout=timeout_seconds * 1000,
        )
        await page.wait_for_timeout(1200)

        # Ensure the requested symbol exists before selecting it.
        available = await page.locator("#optSymbol option").evaluate_all(
            """els => els.map(e => String(e.value || '').toUpperCase())"""
        )
        if symbol.upper() not in available:
            result["error"] = "Requested symbol is not present in #optSymbol options."
            return result

        # Capture both request and response. iCharts may issue multiple XHRs;
        # only OptionChainTable_Beta_v19.php is relevant here.
        captured = {"request": None, "response": None}

        def on_request(req):
            if TABLE_MARKER in req.url and req.method.upper() == "POST":
                captured["request"] = req

        page.on("request", on_request)

        # Select through the actual page control.
        await page.select_option("#optSymbol", symbol)

        # Wait for iCharts to generate the table request.
        deadline = time.perf_counter() + timeout_seconds
        while captured["request"] is None and time.perf_counter() < deadline:
            await page.wait_for_timeout(100)

        if captured["request"] is None:
            result["selected_symbol"] = (await _read_page_state(page)).get(
                "selected_symbol", ""
            )
            result["error"] = (
                "No OptionChainTable_Beta_v19.php POST was generated after "
                "the actual symbol selector change."
            )
            return result

        req = captured["request"]
        result["request_url"] = req.url
        result["request_method"] = req.method
        result["request_post_data"] = req.post_data or ""
        result["request_params"] = _extract_form(req.post_data or "")
        result["request_headers"] = {
            k: v for k, v in req.headers.items()
            if k.lower() in {
                "content-type", "referer", "origin", "x-requested-with",
                "accept", "sec-fetch-site", "sec-fetch-mode"
            }
        }

        params = result["request_params"]
        result["captured_expiry"] = params.get("optExpDate", "")
        result["captured_optStrike"] = params.get("optStrike", "")

        # Await the response associated with the captured request.
        try:
            response = await req.response()
        except Exception:
            response = None

        if response is None:
            result["error"] = "Captured request had no response object."
            return result

        result["request_http"] = response.status
        body = await response.text()

        try:
            data = json.loads(body)
        except Exception as exc:
            result["error"] = (
                f"Captured response was not JSON: {exc}; body={body[:300]!r}"
            )
            return result

        if not isinstance(data, dict):
            result["error"] = "Captured response JSON root is not an object."
            return result

        result["server_symbol"] = str(data.get("symbol_1", ""))
        result["response_ATM"] = str(data.get("strikePriceATM", ""))
        result["response_optStrike"] = str(data.get("optStrike", ""))

        rows = data.get("aaData") or []
        if isinstance(rows, list):
            result["response_rows"] = len(rows)
            result["returned_strikes"] = [
                str(row[32])
                for row in rows
                if isinstance(row, list) and len(row) > 32
            ]

        atm = result["response_ATM"].strip()
        result["atm_in_returned_strikes"] = (
            bool(atm) and atm in {x.strip() for x in result["returned_strikes"]}
        )

        page_state = await _read_page_state(page)
        result["selected_symbol"] = page_state.get("selected_symbol", "")

        result["pass"] = (
            response.status == 200
            and result["selected_symbol"].upper() == symbol.upper()
            and result["server_symbol"].upper() == symbol.upper()
            and result["response_rows"] > 0
            and result["atm_in_returned_strikes"]
        )

        if not result["pass"] and not result["error"]:
            result["error"] = (
                "Captured response failed validation: "
                f"selected={result['selected_symbol']!r}, "
                f"server={result['server_symbol']!r}, "
                f"rows={result['response_rows']}, "
                f"ATM={result['response_ATM']!r}, "
                f"ATM_in_rows={result['atm_in_returned_strikes']}"
            )

        return result

    except Exception as exc:
        result["error"] = str(exc)
        return result

    finally:
        result["elapsed_ms"] = round((time.perf_counter() - started) * 1000, 1)
        await page.close()


async def run_optionchain_request_capture_probe(
    context, symbols, timeout_seconds=30
):
    started = time.perf_counter()

    # Sequential intentionally: symbol changes are browser state operations.
    results = []
    for symbol in symbols:
        results.append(await _one(context, symbol, timeout_seconds))

    passed = sum(bool(r.get("pass")) for r in results)
    return {
        "test": "Option Chain Actual Request Capture Probe",
        "requested": len(symbols),
        "passed": passed,
        "failed": len(symbols) - passed,
        "elapsed_ms": round((time.perf_counter() - started) * 1000, 1),
        "results": results,
    }
