"""
=========================================================
NTIS Replay Package Cleaner
Version : 1.0
Purpose :
    Clean temporary files generated by
    the Historical Replay Engine.
=========================================================
"""

from pathlib import Path


class ReplayCleaner:

    TEMP_PATTERNS = [
        "*.tmp",
        "*.temp",
        "*.bak",
        "*.cache",
        "*.log",
        "__pycache__",
    ]

    def __init__(self, replay_folder):

        self.replay_folder = Path(replay_folder)

    def clean(self):

        removed = []

        for pattern in self.TEMP_PATTERNS:

            for item in self.replay_folder.rglob(pattern):

                try:

                    if item.is_dir():

                        for child in item.rglob("*"):

                            if child.is_file():
                                child.unlink()

                        item.rmdir()

                    else:

                        item.unlink()

                    removed.append(item)

                except Exception:
                    pass

        return removed

    def report(self):

        removed = self.clean()

        print("=" * 60)
        print("NTIS REPLAY CLEANER")
        print("=" * 60)

        print(f"Items Removed : {len(removed)}")

        for item in removed:
            print(item)

        print("=" * 60)


if __name__ == "__main__":

    ReplayCleaner(".").report()